// world.js — Clawd's Quest: an overworld of 3×3 screens and a three-room dungeon. Each room is 16×11 tiles.
//
// Overworld:  T tree  b bush (cut it)  r rock  w water  . grass  , path  s sand  f flowers  > stairs down
//             S sign  H heart container  d ink drop
// Dungeon:    # wall  _ floor  D locked door  C cracked wall (bomb it)  c chest  < stairs up  l torch
// Creatures:  P start  o ink spitter  k paper knight  m moth  B the Ink Kraken
// Neighbouring rooms line up at row 5 (east/west) and columns 7–8 (north/south).

const WORLD = {
  over: {
    '0,0': [
      'TTTTTTTTTTTTTTTT',
      'T..TT....TT....T',
      'T.TbbbT.....f..T',
      'T.b.H.b..m.....T',
      'T.TbbbT........T',
      'T...............',
      'T....f....TT...T',
      'T..m......TT...T',
      'T..............T',
      'T......f.......T',
      'TTTTTTT..TTTTTTT',
    ],
    '1,0': [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T....rrrrrr....T',
      'T....r....r....T',
      'T....r.>..r....T',
      '.......,,.......',
      'T......,,......T',
      'T..k...,,...k..T',
      'T......,,......T',
      'T......,,......T',
      'TTTTTTT..TTTTTTT',
    ],
    '2,0': [
      'TTTTTTTTTTTTTTTT',
      'Tsssswwwwwwsss.T',
      'Tssswwwwwwwwss.T',
      'Tss.wwwwwwwws..T',
      'Ts..swwwwwwss..T',
      '....ssswwwss...T',
      'T..o..sssss..o.T',
      'T..............T',
      'T....dd..dd....T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    '0,1': [
      'TTTTTTT..TTTTTTT',
      'T.T..T....T..T.T',
      'T....m.........T',
      'T.T..T....T..T.T',
      'T..............T',
      'T..m............',
      'T.T..T....T..T.T',
      'T.......m......T',
      'T.T..T....T..T.T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    '1,1': [
      'TTTTTTT..TTTTTTT',
      'T......,,......T',
      'T..r...,,...r..T',
      'T......,,......T',
      'T..o...,,...o..T',
      '.,,,,,,,,,,,,,,.',
      'T......,,......T',
      'T..r...,,...r..T',
      'T......,,..o...T',
      'T......,,......T',
      'TTTTTTT..TTTTTTT',
    ],
    '2,1': [
      'TTTTTTT..TTTTTTT',
      'T..r......r....T',
      'T.....k........T',
      'T..rr.....rr...T',
      'T..............T',
      '..........k....T',
      'T..rr.....rr...T',
      'T..............T',
      'T..r...k...r...T',
      'T..............T',
      'TTTTTTT..TTTTTTT',
    ],
    '0,2': [
      'TTTTTTT..TTTTTTT',
      'T.ff...........T',
      'T.ff..S....ff..T',
      'T..........ff..T',
      'T....ffff......T',
      'T....ffff.......',
      'T..............T',
      'T..o.......o...T',
      'T..............T',
      'T.ff.......ff..T',
      'TTTTTTTTTTTTTTTT',
    ],
    '1,2': [
      'TTTTTTT..TTTTTTT',
      'T..............T',
      'T..ff......ff..T',
      'T....,,,,,,....T',
      'T....,....,....T',
      '.....,.P..,.....',
      'T....,....,....T',
      'T..S.,,,,,,....T',
      'T..............T',
      'T..b........b..T',
      'TTTTTTTTTTTTTTTT',
    ],
    '2,2': [
      'TTTTTTT..TTTTTTT',
      'T..............T',
      'T.wwww....bbb..T',
      'T.wwww....bdb..T',
      'T.wwww....bbb..T',
      '...............T',
      'T..o...........T',
      'T.......wwwww..T',
      'T..d....wwwww..T',
      'T.......wwwww..T',
      'TTTTTTTTTTTTTTTT',
    ],
  },
  dun: {
    '0,2': [
      '#######DD#######',
      '#______________#',
      '#_l__________l_#',
      '#______________#',
      '#___o______o___#',
      '#______________#',
      '#______o_______#',
      '#______________#',
      '#_l__________l_#',
      '#______<<______#',
      '################',
    ],
    '0,1': [
      '#######CC#######',
      '#______________#',
      '#_l____c_____l_#',
      '#______________#',
      '#__k________k__#',
      '#______________#',
      '#____##__##____#',
      '#______________#',
      '#_l__________l_#',
      '#______________#',
      '#######__#######',
    ],
    '0,0': [
      '################',
      '#______________#',
      '#______________#',
      '#__l________l__#',
      '#______________#',
      '#______B_______#',
      '#______________#',
      '#__l________l__#',
      '#______________#',
      '#______________#',
      '#######__#######',
    ],
  },
  signs: {
    'over:1,2': ['잉크 문어가 황금 펜촉을 훔쳐 갔어! 북쪽 동굴로 가 봐. (A: 연필 검)', 'The Ink Kraken stole the Golden Nib! Head for the cave up north. (A: pencil sword)'],
    'over:0,2': ['덤불은 칼로 벨 수 있어. 북서쪽 숲 덤불 속에 뭔가 있대.', 'Bushes can be cut. Something hides in the bushes of the north-west wood.'],
  },
};
